services:
  - type: web
    name: django-blog
    env: python
    buildCommand: ""
    startCommand: gunicorn django_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: SECRET_KEY
        value: your-secret-key-here
	