services:
  - type: web
    name: django-blog
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn django_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
